name: Check Release Version

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  check-version-exists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if release exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_EXISTS=$(gh release view ${{ steps.version.outputs.version }} --json url -q '.url' 2>/dev/null || echo "false")
          if [ "$RELEASE_EXISTS" != "false" ]; then
            echo "❌ Release ${{ steps.version.outputs.version }} already exists. Please update the version in package.json."
            exit 1
          fi
